### ISSUE TITLE
common.jsに移した`rotate`関数を呼び出す際に`ReferenceError`が発生する。

### ISSUE THREAD

**Issue by zaki3mymy** [zaki3mymy/tategaki-copy#4]
公式ドキュメントの以下の記載部分によって引き起こされるエラーと思われる。

>Be aware that the injected function is a copy of the function referenced in the chrome.scripting.executeScript call, not the original function itself. As a result, the function's body must be self contained; references to variables outside of the function will cause the content script to throw a [ReferenceError](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError).
(引用元: https://developer.chrome.com/docs/extensions/mv3/content_scripts/#programmatic)
>
>(Google翻訳)
>chrome.scripting.executeScript挿入された関数は、元の関数そのものではなく、呼び出しで参照された関数のコピーであることに注意してください。結果として、関数の本体は自己完結型である必要があります。関数の外部の変数を参照すると、コンテンツ スクリプトが をスローします[ReferenceError](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError)。

**Comment by zaki3mymy** [comment]
`args:`で`rotate`を渡そうとすると以下のエラーが出る。おそらく関数を引数として渡すのは許されていないっぽい。

>Error in event handler: TypeError: Error in invocation of scripting.executeScript(scripting.ScriptInjection injection, optional function callback): Error at parameter 'injection': Error at property 'args': Error at index 0: Value is unserializable. at chrome-extension://pcikbmmeafmiaaemomjeglnjcdagdfgb/background.js:36:24

**Comment by zaki3mymy** [comment]
コンテキストメニューのクリックイベントで`executeScript`を使わずに直接関数を呼び出すと、
```js
// click event
chrome.contextMenus.onClicked.addListener((info, tab) => {
  switch (info.menuItemId) {
    case "copy":
      // chrome.scripting.executeScript({
      //   target: { tabId: tab.id },
      //   function: copy,
      // });
      copy()
      break;
})
```

以下のようなエラーとなる。
>Error in event handler: ReferenceError: window is not defined at copy (chrome-extension://pcikbmmeafmiaaemomjeglnjcdagdfgb/background.js:54:24) at chrome-extension://pcikbmmeafmiaaemomjeglnjcdagdfgb/background.js:41:7

これはservice workerで`window`が使えないという縛り。

service worker からcontent scripts にメッセージを送って、content scripts からcommon.jsを呼び出すのが正しい？
